### ISSUE TITLE
Using this template

### ISSUE THREAD

**Issue by Abuamany** [hadyrashwan/concerto_ipsative_template#1]
I am interest to using ipsative format at concerto, pls advice us to using this template.

**Comment by hadyrashwan** [comment]
just import the .concerto file to concerto works with 2.171 and 2.186
then when making a questionare componet just select the template instead of the default one
you have one that divides the questions to two blocks and another one as a one block

**Comment by Abuamany** [comment]
Many Thanks, if I want develop questions like this (example for DiSC Questionnare), I should develop 4 block, right?
![behavior jpg w560h405](https://user-images.githubusercontent.com/16170999/27110981-367618c0-50d7-11e7-8be8-3cbbd7456898.jpg)
 Many thanks.

**Comment by Abuamany** [comment]
I have develop with one block template, and the output like this
![screenshot from 2017-06-14 12-23-36](https://user-images.githubusercontent.com/16170999/27116710-f430f39c-50fc-11e7-9333-5fb08d9c0a86.png)

**Comment by hadyrashwan** [comment]
yes you will only have one answer per column that's the idea . for the checking on all the answers I did make the button template which disable the next untell you choose one in each column

**Comment by Abuamany** [comment]
Many Thanks

**Comment by hadyrashwan** [comment]
Im late , sorry I was so busy . anyway , I did update the one ipsative template

**Comment by Abuamany** [comment]
Many Thanks, I was try and run smoothly, btw we have develop LBAII pls find attach questionnare and scoring system.... We have difficulty to show the questions (as variables).
[68191LBAIIScoring.pdf](https://github.com/hadyrashwan/concerto_ipsative_template/files/1083979/68191LBAIIScoring.pdf)
